/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatingTo37RouteImport } from './routes/updating-to-3-7'
import { Route as UpdatingTo36RouteImport } from './routes/updating-to-3-6'
import { Route as TransitionComponentsRouteImport } from './routes/transition-components'
import { Route as SurfaceSlotsRouteImport } from './routes/surface-slots'
import { Route as StackTypesRouteImport } from './routes/stack-types'
import { Route as SnapPointsRouteImport } from './routes/snap-points'
import { Route as SharedElementsRouteImport } from './routes/shared-elements'
import { Route as RevealRouteImport } from './routes/reveal'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as QuickStartRouteImport } from './routes/quick-start'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as OverlaysRouteImport } from './routes/overlays'
import { Route as NavigationZoomRouteImport } from './routes/navigation-zoom'
import { Route as MigratingTo34RouteImport } from './routes/migrating-to-3-4'
import { Route as InstallationRouteImport } from './routes/installation'
import { Route as IndependentStacksRouteImport } from './routes/independent-stacks'
import { Route as InactiveBehaviorRouteImport } from './routes/inactive-behavior'
import { Route as GesturesRouteImport } from './routes/gestures'
import { Route as GestureOwnershipRouteImport } from './routes/gesture-ownership'
import { Route as ExpoRouterRouteImport } from './routes/expo-router'
import { Route as CustomAnimationsRouteImport } from './routes/custom-animations'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as CaveatsRouteImport } from './routes/caveats'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V4NextIndexRouteImport } from './routes/v4-next.index'
import { Route as RecipesModalRouteImport } from './routes/recipes.modal'

const UpdatingTo37Route = UpdatingTo37RouteImport.update({
  id: '/updating-to-3-7',
  path: '/updating-to-3-7',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatingTo36Route = UpdatingTo36RouteImport.update({
  id: '/updating-to-3-6',
  path: '/updating-to-3-6',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitionComponentsRoute = TransitionComponentsRouteImport.update({
  id: '/transition-components',
  path: '/transition-components',
  getParentRoute: () => rootRouteImport,
} as any)
const SurfaceSlotsRoute = SurfaceSlotsRouteImport.update({
  id: '/surface-slots',
  path: '/surface-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const StackTypesRoute = StackTypesRouteImport.update({
  id: '/stack-types',
  path: '/stack-types',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapPointsRoute = SnapPointsRouteImport.update({
  id: '/snap-points',
  path: '/snap-points',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedElementsRoute = SharedElementsRouteImport.update({
  id: '/shared-elements',
  path: '/shared-elements',
  getParentRoute: () => rootRouteImport,
} as any)
const RevealRoute = RevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickStartRoute = QuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysRoute = OverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationZoomRoute = NavigationZoomRouteImport.update({
  id: '/navigation-zoom',
  path: '/navigation-zoom',
  getParentRoute: () => rootRouteImport,
} as any)
const MigratingTo34Route = MigratingTo34RouteImport.update({
  id: '/migrating-to-3-4',
  path: '/migrating-to-3-4',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationRoute = InstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndependentStacksRoute = IndependentStacksRouteImport.update({
  id: '/independent-stacks',
  path: '/independent-stacks',
  getParentRoute: () => rootRouteImport,
} as any)
const InactiveBehaviorRoute = InactiveBehaviorRouteImport.update({
  id: '/inactive-behavior',
  path: '/inactive-behavior',
  getParentRoute: () => rootRouteImport,
} as any)
const GesturesRoute = GesturesRouteImport.update({
  id: '/gestures',
  path: '/gestures',
  getParentRoute: () => rootRouteImport,
} as any)
const GestureOwnershipRoute = GestureOwnershipRouteImport.update({
  id: '/gesture-ownership',
  path: '/gesture-ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpoRouterRoute = ExpoRouterRouteImport.update({
  id: '/expo-router',
  path: '/expo-router',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomAnimationsRoute = CustomAnimationsRouteImport.update({
  id: '/custom-animations',
  path: '/custom-animations',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CaveatsRoute = CaveatsRouteImport.update({
  id: '/caveats',
  path: '/caveats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V4NextIndexRoute = V4NextIndexRouteImport.update({
  id: '/v4-next/',
  path: '/v4-next/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesModalRoute = RecipesModalRouteImport.update({
  id: '/recipes/modal',
  path: '/recipes/modal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/caveats': typeof CaveatsRoute
  '/components': typeof ComponentsRoute
  '/custom-animations': typeof CustomAnimationsRoute
  '/expo-router': typeof ExpoRouterRoute
  '/gesture-ownership': typeof GestureOwnershipRoute
  '/gestures': typeof GesturesRoute
  '/inactive-behavior': typeof InactiveBehaviorRoute
  '/independent-stacks': typeof IndependentStacksRoute
  '/installation': typeof InstallationRoute
  '/migrating-to-3-4': typeof MigratingTo34Route
  '/navigation-zoom': typeof NavigationZoomRoute
  '/overlays': typeof OverlaysRoute
  '/presets': typeof PresetsRoute
  '/quick-start': typeof QuickStartRoute
  '/reference': typeof ReferenceRoute
  '/reveal': typeof RevealRoute
  '/shared-elements': typeof SharedElementsRoute
  '/snap-points': typeof SnapPointsRoute
  '/stack-types': typeof StackTypesRoute
  '/surface-slots': typeof SurfaceSlotsRoute
  '/transition-components': typeof TransitionComponentsRoute
  '/updating-to-3-6': typeof UpdatingTo36Route
  '/updating-to-3-7': typeof UpdatingTo37Route
  '/recipes/modal': typeof RecipesModalRoute
  '/v4-next/': typeof V4NextIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/caveats': typeof CaveatsRoute
  '/components': typeof ComponentsRoute
  '/custom-animations': typeof CustomAnimationsRoute
  '/expo-router': typeof ExpoRouterRoute
  '/gesture-ownership': typeof GestureOwnershipRoute
  '/gestures': typeof GesturesRoute
  '/inactive-behavior': typeof InactiveBehaviorRoute
  '/independent-stacks': typeof IndependentStacksRoute
  '/installation': typeof InstallationRoute
  '/migrating-to-3-4': typeof MigratingTo34Route
  '/navigation-zoom': typeof NavigationZoomRoute
  '/overlays': typeof OverlaysRoute
  '/presets': typeof PresetsRoute
  '/quick-start': typeof QuickStartRoute
  '/reference': typeof ReferenceRoute
  '/reveal': typeof RevealRoute
  '/shared-elements': typeof SharedElementsRoute
  '/snap-points': typeof SnapPointsRoute
  '/stack-types': typeof StackTypesRoute
  '/surface-slots': typeof SurfaceSlotsRoute
  '/transition-components': typeof TransitionComponentsRoute
  '/updating-to-3-6': typeof UpdatingTo36Route
  '/updating-to-3-7': typeof UpdatingTo37Route
  '/recipes/modal': typeof RecipesModalRoute
  '/v4-next': typeof V4NextIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/caveats': typeof CaveatsRoute
  '/components': typeof ComponentsRoute
  '/custom-animations': typeof CustomAnimationsRoute
  '/expo-router': typeof ExpoRouterRoute
  '/gesture-ownership': typeof GestureOwnershipRoute
  '/gestures': typeof GesturesRoute
  '/inactive-behavior': typeof InactiveBehaviorRoute
  '/independent-stacks': typeof IndependentStacksRoute
  '/installation': typeof InstallationRoute
  '/migrating-to-3-4': typeof MigratingTo34Route
  '/navigation-zoom': typeof NavigationZoomRoute
  '/overlays': typeof OverlaysRoute
  '/presets': typeof PresetsRoute
  '/quick-start': typeof QuickStartRoute
  '/reference': typeof ReferenceRoute
  '/reveal': typeof RevealRoute
  '/shared-elements': typeof SharedElementsRoute
  '/snap-points': typeof SnapPointsRoute
  '/stack-types': typeof StackTypesRoute
  '/surface-slots': typeof SurfaceSlotsRoute
  '/transition-components': typeof TransitionComponentsRoute
  '/updating-to-3-6': typeof UpdatingTo36Route
  '/updating-to-3-7': typeof UpdatingTo37Route
  '/recipes/modal': typeof RecipesModalRoute
  '/v4-next/': typeof V4NextIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adapters'
    | '/caveats'
    | '/components'
    | '/custom-animations'
    | '/expo-router'
    | '/gesture-ownership'
    | '/gestures'
    | '/inactive-behavior'
    | '/independent-stacks'
    | '/installation'
    | '/migrating-to-3-4'
    | '/navigation-zoom'
    | '/overlays'
    | '/presets'
    | '/quick-start'
    | '/reference'
    | '/reveal'
    | '/shared-elements'
    | '/snap-points'
    | '/stack-types'
    | '/surface-slots'
    | '/transition-components'
    | '/updating-to-3-6'
    | '/updating-to-3-7'
    | '/recipes/modal'
    | '/v4-next/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adapters'
    | '/caveats'
    | '/components'
    | '/custom-animations'
    | '/expo-router'
    | '/gesture-ownership'
    | '/gestures'
    | '/inactive-behavior'
    | '/independent-stacks'
    | '/installation'
    | '/migrating-to-3-4'
    | '/navigation-zoom'
    | '/overlays'
    | '/presets'
    | '/quick-start'
    | '/reference'
    | '/reveal'
    | '/shared-elements'
    | '/snap-points'
    | '/stack-types'
    | '/surface-slots'
    | '/transition-components'
    | '/updating-to-3-6'
    | '/updating-to-3-7'
    | '/recipes/modal'
    | '/v4-next'
  id:
    | '__root__'
    | '/'
    | '/adapters'
    | '/caveats'
    | '/components'
    | '/custom-animations'
    | '/expo-router'
    | '/gesture-ownership'
    | '/gestures'
    | '/inactive-behavior'
    | '/independent-stacks'
    | '/installation'
    | '/migrating-to-3-4'
    | '/navigation-zoom'
    | '/overlays'
    | '/presets'
    | '/quick-start'
    | '/reference'
    | '/reveal'
    | '/shared-elements'
    | '/snap-points'
    | '/stack-types'
    | '/surface-slots'
    | '/transition-components'
    | '/updating-to-3-6'
    | '/updating-to-3-7'
    | '/recipes/modal'
    | '/v4-next/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptersRoute: typeof AdaptersRoute
  CaveatsRoute: typeof CaveatsRoute
  ComponentsRoute: typeof ComponentsRoute
  CustomAnimationsRoute: typeof CustomAnimationsRoute
  ExpoRouterRoute: typeof ExpoRouterRoute
  GestureOwnershipRoute: typeof GestureOwnershipRoute
  GesturesRoute: typeof GesturesRoute
  InactiveBehaviorRoute: typeof InactiveBehaviorRoute
  IndependentStacksRoute: typeof IndependentStacksRoute
  InstallationRoute: typeof InstallationRoute
  MigratingTo34Route: typeof MigratingTo34Route
  NavigationZoomRoute: typeof NavigationZoomRoute
  OverlaysRoute: typeof OverlaysRoute
  PresetsRoute: typeof PresetsRoute
  QuickStartRoute: typeof QuickStartRoute
  ReferenceRoute: typeof ReferenceRoute
  RevealRoute: typeof RevealRoute
  SharedElementsRoute: typeof SharedElementsRoute
  SnapPointsRoute: typeof SnapPointsRoute
  StackTypesRoute: typeof StackTypesRoute
  SurfaceSlotsRoute: typeof SurfaceSlotsRoute
  TransitionComponentsRoute: typeof TransitionComponentsRoute
  UpdatingTo36Route: typeof UpdatingTo36Route
  UpdatingTo37Route: typeof UpdatingTo37Route
  RecipesModalRoute: typeof RecipesModalRoute
  V4NextIndexRoute: typeof V4NextIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updating-to-3-7': {
      id: '/updating-to-3-7'
      path: '/updating-to-3-7'
      fullPath: '/updating-to-3-7'
      preLoaderRoute: typeof UpdatingTo37RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updating-to-3-6': {
      id: '/updating-to-3-6'
      path: '/updating-to-3-6'
      fullPath: '/updating-to-3-6'
      preLoaderRoute: typeof UpdatingTo36RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transition-components': {
      id: '/transition-components'
      path: '/transition-components'
      fullPath: '/transition-components'
      preLoaderRoute: typeof TransitionComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surface-slots': {
      id: '/surface-slots'
      path: '/surface-slots'
      fullPath: '/surface-slots'
      preLoaderRoute: typeof SurfaceSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack-types': {
      id: '/stack-types'
      path: '/stack-types'
      fullPath: '/stack-types'
      preLoaderRoute: typeof StackTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snap-points': {
      id: '/snap-points'
      path: '/snap-points'
      fullPath: '/snap-points'
      preLoaderRoute: typeof SnapPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-elements': {
      id: '/shared-elements'
      path: '/shared-elements'
      fullPath: '/shared-elements'
      preLoaderRoute: typeof SharedElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reveal': {
      id: '/reveal'
      path: '/reveal'
      fullPath: '/reveal'
      preLoaderRoute: typeof RevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-start': {
      id: '/quick-start'
      path: '/quick-start'
      fullPath: '/quick-start'
      preLoaderRoute: typeof QuickStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays': {
      id: '/overlays'
      path: '/overlays'
      fullPath: '/overlays'
      preLoaderRoute: typeof OverlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation-zoom': {
      id: '/navigation-zoom'
      path: '/navigation-zoom'
      fullPath: '/navigation-zoom'
      preLoaderRoute: typeof NavigationZoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrating-to-3-4': {
      id: '/migrating-to-3-4'
      path: '/migrating-to-3-4'
      fullPath: '/migrating-to-3-4'
      preLoaderRoute: typeof MigratingTo34RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/independent-stacks': {
      id: '/independent-stacks'
      path: '/independent-stacks'
      fullPath: '/independent-stacks'
      preLoaderRoute: typeof IndependentStacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inactive-behavior': {
      id: '/inactive-behavior'
      path: '/inactive-behavior'
      fullPath: '/inactive-behavior'
      preLoaderRoute: typeof InactiveBehaviorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestures': {
      id: '/gestures'
      path: '/gestures'
      fullPath: '/gestures'
      preLoaderRoute: typeof GesturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gesture-ownership': {
      id: '/gesture-ownership'
      path: '/gesture-ownership'
      fullPath: '/gesture-ownership'
      preLoaderRoute: typeof GestureOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expo-router': {
      id: '/expo-router'
      path: '/expo-router'
      fullPath: '/expo-router'
      preLoaderRoute: typeof ExpoRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-animations': {
      id: '/custom-animations'
      path: '/custom-animations'
      fullPath: '/custom-animations'
      preLoaderRoute: typeof CustomAnimationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caveats': {
      id: '/caveats'
      path: '/caveats'
      fullPath: '/caveats'
      preLoaderRoute: typeof CaveatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4-next/': {
      id: '/v4-next/'
      path: '/v4-next'
      fullPath: '/v4-next/'
      preLoaderRoute: typeof V4NextIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/modal': {
      id: '/recipes/modal'
      path: '/recipes/modal'
      fullPath: '/recipes/modal'
      preLoaderRoute: typeof RecipesModalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptersRoute: AdaptersRoute,
  CaveatsRoute: CaveatsRoute,
  ComponentsRoute: ComponentsRoute,
  CustomAnimationsRoute: CustomAnimationsRoute,
  ExpoRouterRoute: ExpoRouterRoute,
  GestureOwnershipRoute: GestureOwnershipRoute,
  GesturesRoute: GesturesRoute,
  InactiveBehaviorRoute: InactiveBehaviorRoute,
  IndependentStacksRoute: IndependentStacksRoute,
  InstallationRoute: InstallationRoute,
  MigratingTo34Route: MigratingTo34Route,
  NavigationZoomRoute: NavigationZoomRoute,
  OverlaysRoute: OverlaysRoute,
  PresetsRoute: PresetsRoute,
  QuickStartRoute: QuickStartRoute,
  ReferenceRoute: ReferenceRoute,
  RevealRoute: RevealRoute,
  SharedElementsRoute: SharedElementsRoute,
  SnapPointsRoute: SnapPointsRoute,
  StackTypesRoute: StackTypesRoute,
  SurfaceSlotsRoute: SurfaceSlotsRoute,
  TransitionComponentsRoute: TransitionComponentsRoute,
  UpdatingTo36Route: UpdatingTo36Route,
  UpdatingTo37Route: UpdatingTo37Route,
  RecipesModalRoute: RecipesModalRoute,
  V4NextIndexRoute: V4NextIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
