import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	docsSidebar: [
		// ── Sections ──────────────────────────────────────────
		{
			type: "category",
			label: "Sections",
			collapsible: false,
			collapsed: false,
			items: [
				"intro",
				"getting-started/installation",
				"getting-started/quickstart",
				"core-mental-model/index",
				"stack-variants/index",
				"shared-elements-bounds/index",
				"gestures-snap-points/index",
				"recipes/index",
				"migration/index",
			],
		},

		// ── Presets ───────────────────────────────────────────
		{
			type: "category",
			label: "Presets",
			collapsible: false,
			collapsed: false,
			items: ["presets/index"],
		},

		// ── Components ────────────────────────────────────────
		{
			type: "category",
			label: "Components",
			collapsible: false,
			collapsed: false,
			items: [
				"api/index",
				{
					type: "autogenerated",
					dirName: "api/reference",
				},
			],
		},
	],
};

export default sidebars;
