import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	docsSidebar: [
		"intro",
		{
			type: "category",
			label: "Getting Started",
			items: [
				"getting-started/installation",
				"getting-started/quickstart",
			],
		},
		{
			type: "category",
			label: "Core Mental Model",
			items: ["core-mental-model/index"],
		},
		{
			type: "category",
			label: "Stack Variants",
			items: ["stack-variants/index"],
		},
		{
			type: "category",
			label: "Presets",
			items: ["presets/index"],
		},
		{
			type: "category",
			label: "Shared Elements / Bounds",
			items: ["shared-elements-bounds/index"],
		},
		{
			type: "category",
			label: "Gestures / Snap Points",
			items: ["gestures-snap-points/index"],
		},
		{
			type: "category",
			label: "Recipes",
			items: ["recipes/index"],
		},
		{
			type: "category",
			label: "Migration",
			items: ["migration/index"],
		},
		{
			type: "category",
			label: "Release Notes",
			items: [
				"release-notes/index",
				"release-notes/3-3-stable",
				"release-notes/3-4-next",
			],
		},
		{
			type: "category",
			label: "API Reference",
			items: [
				"api/index",
				{
					type: "autogenerated",
					dirName: "api/reference",
				},
			],
		},
	],
};

export default sidebars;
